package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Проверить работу поиска")
    void generatedTest() {
        step("Открыть https://vsenauka.ru/knigi/vsenauchnyie-knigi/", () -> {
            // todo
        });

        step("В поле Автор установить значение Саган", () -> {
            // todo
        });

        step("В поле Название установить значение Голубая", () -> {
            // todo
        });

        step("Нажать Найти", () -> {
            // todo
        });

        step("Ожидаемый результат: в поиске выдана 1 книга Саган, Карл", () -> {
            // todo
        });

        step("Голубая точка. Космическое будущее человечества", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://vsenauka.ru/knigi/vsenauchnyie-knigi/'", () ->
            open("https://vsenauka.ru/knigi/vsenauchnyie-knigi/"));

        step("Page title should have text 'Навигатор | Всенаука'", () -> {
            String expectedTitle = "Навигатор | Всенаука";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://vsenauka.ru/knigi/vsenauchnyie-knigi/'", () ->
            open("https://vsenauka.ru/knigi/vsenauchnyie-knigi/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}